server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:cheques;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

security:
  jwt:
    secret: "change-this-dev-secret-please-use-32-bytes-minimum"
    expirationSeconds: 3600

sayad:
  base-url: http://localhost:8081/sayad

logging:
  level:
    root: INFO
    org.springframework.security: INFO


